package:
  name: chainer
  version: "1.1.1"

build:
  number: 1

source:
  fn: chainer-1.1.1.tar.gz
  url: https://pypi.python.org/packages/source/c/chainer/chainer-1.1.1.tar.gz
  md5: f785c33ac0c2cdb950183ca8a2299513

requirements:
  build:
    - python
    - setuptools
    - nose
    - numpy
    - protobuf
    - six >=1.9.0

  run:
    - python
    - numpy
    - protobuf
    - six >=1.9.0

test:
  imports:
    - chainer
    - chainer.cudnn
    - chainer.functions
    - chainer.functions.caffe
    - chainer.optimizers
    - chainer.testing
    - chainer.utils

  requires:
    - nose

about:
  home: http://chainer.org/
  license: MIT license
  summary: 'A flexible framework of neural networks'
