package:
  name: chainer
  version: {{ environ['GIT_DESCRIBE_TAG'][1:] }}

build:
  number: 0

source:
  git_rev: v1.2.0
  git_url: https://github.com/pfnet/chainer.git

requirements:
  build:
    - python
    - setuptools
    - nose
    - numpy
    - protobuf
    - six >=1.9.0

  run:
    - python
    - numpy
    - protobuf
    - six >=1.9.0

test:
  imports:
    - chainer
    - chainer.cudnn
    - chainer.functions
    - chainer.functions.caffe
    - chainer.optimizers
    - chainer.testing
    - chainer.utils

  requires:
    - nose

about:
  home: http://chainer.org/
  license: MIT license
  summary: 'A flexible framework of neural networks'
