package:
  name: chainer
  version: 0

build:
  number: 0

source:
  git_rev: v1.3.2
  git_url: https://github.com/pfnet/chainer.git

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.9
    - six >=1.9.0
    - protobuf
    - filelock
    - nose
    - mock

  run:
    - python
    - numpy >=1.9
    - six >=1.9.0
    - protobuf
    - filelock

test:
  imports:
    - chainer
    - chainer.functions
    - chainer.optimizers
    - chainer.utils

about:
  home: http://chainer.org/
  license: MIT license
  summary: 'A flexible framework of neural networks'
