package:
  name: imolecule
  version: "0.1.9"

build:
  number: 0

source:
  fn: imolecule-0.1.9.tar.gz
  url: https://pypi.python.org/packages/source/i/imolecule/imolecule-0.1.9.tar.gz
  md5: c097b65b510d416032f18914dbc36773

requirements:
  build:
    - ipython
    - setuptools
    - tornado

  run:
    - ipython

test:
  imports:
    - imolecule

about:
  home: http://patrick-fuller.com/imolecule/
  license: MIT license
  summary: 'An embeddable webGL molecule viewer and file format converter.'
